# Generated by Django 4.2.7 on 2024-05-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phn',
            field=models.IntegerField(null=True),
        ),
    ]
