# Generated by Django 4.2.7 on 2024-05-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employees_age_alter_employees_phn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=180)),
                ('age', models.IntegerField()),
                ('phn', models.IntegerField()),
                ('password', models.CharField(max_length=180)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
    ]
