# Generated by Django 4.2.7 on 2024-05-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_customer_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
