# Generated by Django 4.2.7 on 2024-05-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employees_password_employees_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=180)),
                ('stock', models.IntegerField()),
                ('addDate', models.DateField()),
                ('desc', models.CharField(max_length=880)),
                ('img', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
    ]
