# Generated by Django 4.2.7 on 2024-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
