# Generated by Django 4.2.7 on 2024-05-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchased',
            name='status',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
