# Generated by Django 4.2.7 on 2024-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_purchased_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='status',
            field=models.CharField(default='ordered', max_length=180, null=True),
        ),
    ]
